# Generated by Django 5.2 on 2025-04-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="package_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="medicine_management.packagetypes",
            ),
        ),
        migrations.AlterField(
            model_name="packagetypes",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_types",
                to="medicine_management.medicine",
            ),
        ),
    ]
